version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - gibbon_uploads:/var/www/html/uploads
    networks:
      - gibbon-network
    container_name: gibbon-php
    command: /bin/bash -c "chown -R www-data:www-data /var/www/html && chmod -R 775 /var/www/html && apache2-foreground"

  mysql:
    image: mysql:5.7
    container_name: escola_example
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gibbon-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8082:80"
    networks:
      - gibbon-network

networks:
  gibbon-network:
    driver: bridge

volumes:
  mysql_data:
  gibbon_uploads:
